services:
  frontend:
    image: yayawallet/react-dashboard:latest
    ports:
      - "3000:80"

  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    image: yayawallet/background-service:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq_server

  backend:
    image: yayawallet/python-server:latest
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        python manage.py automate_permissions
        if [ "$DJANGO_SUPERUSER_USERNAME" ] && [ "$DJANGO_SUPERUSER_EMAIL" ] && [ "$DJANGO_SUPERUSER_PASSWORD" ]; then
          python manage.py createsuperuser --noinput || true
        fi
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - worker
    environment:
      - PYTHONUNBUFFERED=1
