version: "3.8"

services:
  react-dashboard:
    image: yayawallet/react-dashboard
    ports:
      - "3030:3030"
    environment:
      - VITE_BASE_URL=http://localhost:4040
    depends_on:
      - nodejs-server

  nodejs-server:
    image: yayawallet/nodejs-server
    ports:
      - "4040:4040"
    env_file:
      - .env

  # python-server:
  # image: yayawallet/python-server
  # ports:
  #   - "8000:8000"
  # env_file:
  #   - .env
