version: '0.1'

services:
  frontend:
    image: yayawallet/yayawallet-sdk-frontend:latest
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:8000

  backend:
    image: yayawallet/yaya-example-python-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
      